#! /bin/sh

NAME=ntpd
DAEMON=/usr/sbin/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
  . /etc/default/$NAME
fi

case "$1" in
  start)
    printf "Starting $NAME: "
    # Copy ntp.tpl to ntp.conf
    if ! [ -e /etc/ntp.conf ]; then
        cat /etc/ntp.tpl > /etc/ntp.conf
    fi

    # allow first adjustment to be big, if year is 1970
    if [ $(date +%Y) == 1970 ]; then
        start-stop-daemon -S -q -x $DAEMON -- -g
    else
        start-stop-daemon -S -q -x $DAEMON
    fi
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping $NAME: "
    start-stop-daemon -K -q -n $NAME
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    echo "Restarting $NAME: "
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
