#!/bin/sh
#
# Start/stop wordclock
#

. /etc/profile.d/locale.sh

PIDFILE=/var/run/wordclock.pid

case "$1" in
  start)
	echo "Starting wordclock..."
	start-stop-daemon -b -S -m -p $PIDFILE -x /usr/sbin/wordclock
	;;
  stop)
	printf "Stopping wordclock..."
	start-stop-daemon -K -o -p $PIDFILE
	;;
  restart|reload)
	"$0" stop
	sleep 1
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
