#!/bin/sh

logger -p user.info -t update "Check update"

if [ ! -f /sys/class/net/wlan0/address ]; then
	logger -p user.err -t update "No wifi dongle! Aborting.";
	exit;
fi;

read DEVICE < /sys/class/net/wlan0/address
HOSTNAME=$(hostname)
LINUX=$(uname -mrsvo)
WORDCLOCK=$(wordclock -v)
UPTIME=$(uptime)
FILESYSTEM=$(cat /mnt/root-ro/build)

DATA="$DEVICE"$'\n'"$HOSTNAME"$'\n'"$LINUX"$'\n'"$WORDCLOCK"$'\n'"$UPTIME"$'\n'"$FILESYSTEM"$'\n';

for i in `seq 1 12`; do
	SCRIPT=$(wget -qO- --body-data="$DATA" --method=POST https://openlarry.de/wordclock/update.php)
	
	if [ $? -eq 0 ]; then
		logger -p user.info -t update "Update check done!";
		eval "$SCRIPT"
		exit;
	else
		if [ $i -lt 12 ]; then
			sleep 60;
		fi;
	fi;
done

logger -p user.err -t update "Update check failed!";
