#!/bin/sh
#
# Start/stop rdnssd
#

PIDFILE=/var/run/rdnssd.pid
MERGEHOOK=/etc/rdnssd/merge-hook

case "$1" in
  start)
	echo "Starting rdnssd..."
	if [ ! -d "/var/run/rdnssd" ]; then
		mkdir -p /var/run/rdnssd
		chown rdnssd:nogroup /var/run/rdnssd
		chmod 0755 /var/run/rdnssd
	fi
	start-stop-daemon -S -x /usr/sbin/rdnssd -p $PIDFILE -- -u rdnssd -H $MERGEHOOK
	;;
  stop)
	printf "Stopping rdnssd..."
	start-stop-daemon -K -o -p $PIDFILE
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
