#!/bin/sh
#
# Start/stop autossh
#
set -e

PIDFILE=/var/run/autossh.pid

case "$1" in
  start)
	echo "Starting autossh..."
	
	read MAC < /sys/class/net/wlan0/address
	ADD=$((0x${MAC:13:1}${MAC:15:2}))
	
	env AUTOSSH_PIDFILE=$PIDFILE start-stop-daemon -S -x autossh -- -M $((10982+$ADD*2)) -N -f -o "PubkeyAuthentication=yes" -o "PasswordAuthentication=no" -o "UserKnownHostsFile=/etc/autossh/known_hosts" -i /etc/autossh/id_rsa -R $((2000+$ADD)):localhost:22 -p 34765 -N wordclock@do.openlarry.de
	;;
  stop)
	printf "Stopping autossh..."
	start-stop-daemon -K -o -p $PIDFILE
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
