name: Build WordClock image

on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: true
    - name: install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get -y install build-essential libncurses5-dev git bzr cvs mercurial subversion libc6:i386 unzip bc gcc-multilib g++-multilib 
    - name: make
      run: |
        make olimex_imx233_olinuxino_wordclock_defconfig
        BR2_USE_CCACHE=0 make
    - uses: actions/upload-artifact@v4
      with:
        name: sd-card
        path: output/images/sd-card.img
        overwrite: true
